### ISSUE TITLE
[Help] FRONTEND_URL   我填写了https://xeu.life或者其他都不行

### ISSUE THREAD

**Issue by yuan22** [OXeu/Rin#105]
Fetching FRONTEND_URL
11 | export class PuppeteerError extends Error {
12 |     /**
13 |      * @internal
14 |      */
15 |     constructor(message, options) {
16 |         super(message, options);
             ^
ProtocolError: Protocol error (Page.navigate): Cannot navigate to invalid URL
 code: "undefined"
      at new PuppeteerError (/home/runner/work/Rin/Rin/Rin/node_modules/puppeteer-core/lib/esm/puppeteer/common/Errors.js:16:9)
      at new ProtocolError (:1:[33](https://github.com/yuan22/Rin/actions/runs/9463194228/job/26067814881#step:6:34))
      at new Callback (/home/runner/work/Rin/Rin/Rin/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:93:17)
      at create (/home/runner/work/Rin/Rin/Rin/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:19:26)
      at /home/runner/work/Rin/Rin/Rin/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Frame.js:161:44
      at navigate (/home/runner/work/Rin/Rin/Rin/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Frame.js:159:37)
      at /home/runner/work/Rin/Rin/Rin/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Frame.js:139:17
      at goto (/home/runner/work/Rin/Rin/Rin/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Frame.js:1[34](https://github.com/yuan22/Rin/actions/runs/9463194228/job/26067814881#step:6:35):20)
      at /home/runner/work/Rin/Rin/Rin/node_modules/puppeteer-core/lib/esm/puppeteer/api/Page.js:558:26
      at goto (/home/runner/work/Rin/Rin/Rin/node_modules/puppeteer-core/lib/esm/puppeteer/api/Page.js:557:20)
Bun v1.1.12 (Linux x64 baseline)
Error: Process completed with exit code 1.

**Comment by OXeu** [comment]
正常配置应该是配置环境变量 SEO_BASE_URL 为自己前端地址，在缺少 SEO_BASE_URL 时才会选择使用 FRONTEND_URL 作为 SEO 爬取的地址，但是这里确实是个 bug，只设置 FRONTEND_URL 无法正常工作
